// Authoritative, explainable rule-based Lifestyle Compatibility Index (LCI).
const LCI_WEIGHTS = { cleanliness: 15, foodPreference: 20, noisePreference: 15, sleepSchedule: 15, studyHabit: 10, smoking: 5, drinking: 5, nightCalls: 5, windowPreference: 10 };
const MIN_COMPATIBILITY_SCORE = 50;
function normalize(profile) { const clean = Number(profile.cleanliness); return { cleanliness: Number.isFinite(clean) ? clean : ({ low: 1, medium: 3, high: 5 }[profile.cleanliness] || 3), foodPreference: Array.isArray(profile.foodPreference) ? profile.foodPreference : [profile.dietaryPreference || "no_preference"], noisePreference: profile.noisePreference || "moderate", sleepSchedule: profile.sleepSchedule || "flexible", studyHabit: profile.studyHabit || "flexible", smoking: typeof profile.smoking === "boolean" ? (profile.smoking ? "yes" : "no") : profile.smoking, drinking: typeof profile.drinking === "boolean" ? (profile.drinking ? "yes" : "no") : profile.drinking, nightCalls: profile.nightCalls || "no", windowPreference: profile.windowPreference || "flexible" }; }
const same = (a, b) => a && b && String(a).toLowerCase() === String(b).toLowerCase() ? 1 : 0;
const flexible = (a, b) => a === "flexible" || b === "flexible" ? 1 : same(a, b);
function scale(a, b) { const diff = Math.abs(a - b); return diff === 0 ? 1 : diff === 1 ? .75 : diff === 2 ? .5 : 0; }
function food(a, b) { const x = a.map(String), y = b.map(String); return x.some(v => y.includes(v)) ? 1 : ((x.includes("jain") && y.includes("vegetarian")) || (y.includes("jain") && x.includes("vegetarian"))) ? .8 : 0; }
function lifestyle(a, b) { if (a === b) return 1; return (a === "no" && b === "occasionally") || (b === "no" && a === "occasionally") ? .5 : 0; }
function calculateCompatibility(a, b) { a = normalize(a); b = normalize(b); const factorScores = { cleanliness: scale(a.cleanliness, b.cleanliness), foodPreference: food(a.foodPreference, b.foodPreference), noisePreference: flexible(a.noisePreference, b.noisePreference), sleepSchedule: flexible(a.sleepSchedule, b.sleepSchedule), studyHabit: flexible(a.studyHabit, b.studyHabit), smoking: lifestyle(a.smoking, b.smoking), drinking: lifestyle(a.drinking, b.drinking), nightCalls: lifestyle(a.nightCalls, b.nightCalls), windowPreference: flexible(a.windowPreference, b.windowPreference) }; const compatibilityScore = Math.round(Object.entries(LCI_WEIGHTS).reduce((total, [key, weight]) => total + factorScores[key] * weight, 0)); return { compatibilityScore, compatibilityLevel: getCompatibilityLevel(compatibilityScore), factorScores, matchedFactors: Object.keys(factorScores).filter(k => factorScores[k] >= .75), potentialConflicts: Object.keys(factorScores).filter(k => factorScores[k] < .5) }; }
function getCompatibilityLevel(score) { return score >= 85 ? "Highly Compatible" : score >= 70 ? "Compatible" : score >= 50 ? "Moderately Compatible" : "Low Compatibility"; }
function rankCompatibleRoommates(target, candidates) { return candidates.map(candidate => ({ studentId: candidate.user?._id || candidate.user?.id || candidate._id || candidate.id, name: candidate.name || `${candidate.user?.firstName || ""} ${candidate.user?.lastName || ""}`.trim(), user: candidate.user, ...calculateCompatibility(target, candidate) })).filter(x => x.compatibilityScore >= MIN_COMPATIBILITY_SCORE).sort((a,b) => b.compatibilityScore-a.compatibilityScore); }
module.exports = { LCI_WEIGHTS, MIN_COMPATIBILITY_SCORE, normalize, calculateCompatibility, rankCompatibleRoommates, getCompatibilityLevel };
